wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1665052839.807051
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      3:
      - 2
      - 16
      - 23
      4: 3.9.13
      5: 0.13.4
      8:
      - 1
      - 3
      - 5
name:
  desc: null
  value: default
training:
  desc: null
  value:
    aug_rampup: 10000
    augment: false
    batch: 2
    dataset_p: null
    datasets: Decathlon
    interp_mode:
    - area
    - area
    lr: 0.0001
    max_iter: 100000
    pretrain_name_ite: null
    recon_mode: BCE
    reshape:
    - 128
    - 128
    - 96
    reshape_mode: padding
    weight_decay: 1.0e-05
    weight_mode_loss: null
unet:
  desc: null
  value:
    SE:
    - 0
    - 0
    - 1
    - 1
    - 1
    act: silu
    block: ffmmm
    downscale_mode: avgpool
    expand_ratio:
    - 1
    - 4
    - 4
    - 6
    - 6
    init_mode: effecientnetv2
    input_channels: 1
    num_blocks: 5
    num_c:
    - 4
    - 8
    - 8
    - 16
    - 16
    num_classes: 1
    num_repeat:
    - 1
    - 2
    - 2
    - 4
    - 4
    res_mode: add
    upscale_mode: NDlinear
wandb:
  desc: null
  value: true
